[endpoints]
  gqlEndpoint1 = "http://localhost:8000/subgraphs/name/example1"
  gqlEndpoint2 = "http://localhost:3008/graphql"

[queries]
  queryDir = "../graph-test-watcher/src/gql/queries"
  names = []
  blockDelayInMs = 250

[watcher]
  configpath = "../../graph-test-watcher/environments/local.toml"
  entitiesDir = "../../graph-test-watcher/src/entity"
  endpoint = "gqlEndpoint2"
  verifyState = true
  derivedFields = []

[cache]
  endpoint = "gqlEndpoint1"

  [cache.config]
    name = "subgraph-requests"
    enabled = true
    deleteOnStart = false
