[server]
  host = "127.0.0.1"
  port = 3005

[watch]
  lighthouse = "0xbDA876401576281a1912a20de135F60de6D7d711"

[upstream]
  [upstream.ethServer]
    gqlApiEndpoint = "http://127.0.0.1:8082/graphql"

  [upstream.cache]
    name = "requests"
    enabled = false
    deleteOnStart = false
