[server]
  host = "127.0.0.1"
  port = 3004

[database]
  type = "postgres"
  host = "localhost"
  port = 5432
  database = "uni-info-watcher"
  username = "postgres"
  password = "postgres"
  synchronize = true
  logging = false

  entities = [ "src/entity/**/*.ts" ]
  migrations = [ "src/migration/**/*.ts" ]
  subscribers = [ "src/subscriber/**/*.ts" ]

  [database.cli]
    entitiesDir = "src/entity"
    migrationsDir = "src/migration"
    subscribersDir = "src/subscriber"

[upstream]
  gqlEndpoint = "http://127.0.0.1:8082/graphql"
  gqlSubscriptionEndpoint = "http://127.0.0.1:5000/graphql"

  [upstream.cache]
    name = "requests"
    enabled = false
    deleteOnStart = false

  [upstream.uniWatcher]
    gqlEndpoint = "http://127.0.0.1:3003/graphql"
    gqlSubscriptionEndpoint = "http://127.0.0.1:3003/graphql"

  [upstream.tokenWatcher]
    gqlEndpoint = "http://127.0.0.1:3001/graphql"
    gqlSubscriptionEndpoint = "http://127.0.0.1:3001/graphql"
