[server]
  host = "127.0.0.1"
  port = 3004
  # Use mode demo when running watcher locally.
  # Mode demo whitelists all tokens so that entity values get updated.
  mode = "demo"

[database]
  type = "postgres"
  host = "localhost"
  port = 5432
  database = "uni-info-watcher"
  username = "postgres"
  password = "postgres"
  synchronize = true
  logging = false

[upstream]
  [upstream.ethServer]
    gqlApiEndpoint = "http://127.0.0.1:8082/graphql"
    rpcProviderEndpoint = "http://127.0.0.1:8545"
    blockDelayInMilliSecs = 2000

  [upstream.cache]
    name = "requests"
    enabled = false
    deleteOnStart = false

  [upstream.uniWatcher]
    gqlEndpoint = "http://127.0.0.1:3003/graphql"
    gqlSubscriptionEndpoint = "http://127.0.0.1:3003/graphql"

  [upstream.tokenWatcher]
    gqlEndpoint = "http://127.0.0.1:3001/graphql"
    gqlSubscriptionEndpoint = "http://127.0.0.1:3001/graphql"

[jobQueue]
  dbConnectionString = "postgres://postgres:postgres@localhost/uni-info-watcher-job-queue"
  maxCompletionLagInSecs = 300
  jobDelayInMilliSecs = 1000
  eventsInBatch = 50
