# Watcher URL
url: ""

# Boolean to specify if it is a subgraph watcher
isSubgraph: false

# File path for saving GQL result
gqlResultFilepath: "./result.json"

# Optional parameter to override default GQL query
# Set GQL filepath containing query
graphqlQuery: ""
