[server]
  host = "127.0.0.1"
  port = 3001

[database]
  type = "sqlite"
  database = "out/indexer.db"
  synchronize = true
  logging = false

[upstream]
  gqlEndpoint = "http://127.0.0.1:8083/graphql"

  [upstream.cache]
    name = "requests"
    enabled = true
    deleteOnStart = false
