[server]
  host = "127.0.0.1"
  port = 3001

[database]
  type = "postgres"
  host = "localhost"
  port = 5432
  database = "erc20-watcher"
  username = "postgres"
  password = "postgres"
  synchronize = true
  logging = true

[upstream]
  gqlEndpoint = "http://127.0.0.1:8083/graphql"

  [upstream.cache]
    name = "requests"
    enabled = true
    deleteOnStart = false
