name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  docker_publish:
    name: Push Docker image to Github Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: vars
        run: |
          echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
          echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})
      - name: Docker Login to Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u cerc-io --password-stdin
      - name: Docker Pull
        run: docker pull ghcr.io/cerc-io/watcher-ts:${{steps.vars.outputs.sha}}
      - name: Tag docker image
        run: docker tag ghcr.io/cerc-io/watcher-ts:${{steps.vars.outputs.sha}} ghcr.io/cerc-io/watcher-ts:${{steps.vars.outputs.tag}}
      - name: Docker Push to Github Hub
        run: docker push ghcr.io/cerc-io/watcher-ts:${{steps.vars.outputs.tag}}

  npm_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn
      - name: Run yarn build
        run: |
          yarn build
      - name: Configure git.vdb.to npm registry
        run: |
          npm config set @cerc-io:registry https://git.vdb.to/api/packages/cerc-io/npm/
      - name: Authenticate to git.vdb.to registry
        run: |
          npm config set -- '//git.vdb.to/api/packages/cerc-io/npm/:_authToken' "${{ secrets.GITEA_PUBLISH_TOKEN }}"
      - name: lerna publish
        run: |
          lerna publish from-package --no-git-tag-version --yes